name: Deploy web app to Azure Static Web Apps
on:
  push:
    branches: [ "main", "southafrica", "retirement" ]

env:
  APP_LOCATION: "/dist"
  API_LOCATION: "api"
  APP_ARTIFACT_LOCATION: "dist"
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
  AZ_WEBAPP_TOKEN: ${{ (github.ref_name == 'southafrica' && secrets.AZ_TOKEN_SOUTHAFRICA) || (github.ref_name == 'retirement' && secrets.AZ_TOKEN_RETIREMENT) || '' }}
  THEME_KEY: ${{ github.ref_name == 'southafrica' && 'southafrica' || github.ref_name == 'retirement' && 'retirement' || 'default' }}

permissions:
  contents: read

jobs:

  build:
    name: Build the WebApp
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0
          cache: 'npm'
          cache-dependency-path: bun.lock

      - name: 📦 Install dependencies
        run: npm install -g bun && bun install

      - name: 🛠️ Build the project
        run: npm run build:prod:${{ env.THEME_KEY }}

      - name: 📤 Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.APP_ARTIFACT_LOCATION }}

  build_and_deploy_job:
    name: Deploy the WebApp
    if: github.ref_name == 'southafrica' || github.ref_name == 'retirement'

    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ⬇️ Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ env.APP_ARTIFACT_LOCATION }}

      - name: 🚀 Deploy
        id: deploy

        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZ_WEBAPP_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ./
